---

- name: Create docker image storage directory.
  file: path={{ docker_registry_storage_path }} state=directory

- name: Ensure docker registry is installed.
  yum: name=docker-registry state=installed

- name: Place docker registry config file.
  template: src=docker-registry.yml.j2 dest=/etc/docker-registry.yml
  notify: restart docker-registry

- name: Place docker sysconfig file.
  template: src=docker.j2 dest=/etc/sysconfig/docker
  notify: restart docker

- name: Ensure docker registry is started and enabled to start at boot.
  service: name=docker-registry state=started enabled=yes
  when: ansible_connection != 'docker'
